{% set name = "napari-features-selector" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-features-selector-{{ version }}.tar.gz
  sha256: 916946ceaccbddd32f84d0b0bdec2d8e652222a6ef61a441baa352787db7668c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - numpy
    - napari
    - pandas
    - python >=3.8
    - qtpy
    - scikit-learn
    - sklearn-genetic-opt

test:
  imports:
    - napari_features_selector
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kumar-sanjeeev/napari-features-selector
  summary: A lightweight widget for features selection.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kumar-sanjeeev
